[project]
name = "framework-assignment"
version = "0.1.0"
description = "Data-Analysis with python libraries"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "seaborn>=0.13.2",
    "streamlit>=1.49.1",
]
